name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name "fDenyTSConnections" -Value 0 -Force

          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389

          Restart-Service TermService -Force


      - name: Create RDP User
        shell: powershell
        run: |
          $password = "ItachiUchiha@1964"

          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires

          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"


      - name: Install Tailscale
        shell: powershell
        run: |
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $file = "$env:TEMP\tailscale.msi"

          Invoke-WebRequest $url -OutFile $file
          Start-Process msiexec.exe -Wait -ArgumentList "/i $file /quiet"
          Remove-Item $file


      - name: Connect Tailscale
        shell: powershell
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up `
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} `
            --hostname=gh-runner-$env:GITHUB_RUN_ID

          Start-Sleep 10

          $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4

          echo "TS_IP=$ip" >> $env:GITHUB_ENV


      - name: Show RDP Info
        shell: powershell
        run: |
          echo "===================="
          echo "IP: $env:TS_IP"
          echo "User: RDP"
          echo "Password: ItachiUchiha@1964"
          echo "===================="

          while ($true) {
            Start-Sleep 300
          }
